[paths]
reactant = "/global/cfs/cdirs/m2834/kumaranu/molecules_kinbotprod_renamed/000_R.xyz"
product = "/global/cfs/cdirs/m2834/kumaranu/molecules_kinbotprod_renamed/000_P.xyz"
model_path = "/global/u2/k/kumaranu/Documents/NewtonNet/example/predict/training_52/models/best_model_state.tar"
settings_path = "/global/u2/k/kumaranu/Documents/NewtonNet/example/predict/training_52/run_scripts/config0.yml"
launchpad_file = "/global/homes/k/kumaranu/fw_config/my_launchpad.yaml"

[run]
tag = "jul1y24c"
